// app/layout.tsx
"use client"
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FlowbiteInitializer from "@/components/FlowbiteInitializer";
import Sidebar from "@/components/Sidebar";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAuthPage = pathname?.startsWith('/login');
  return (
    <html lang="en" data-theme="light" className="w-full h-full">
      <body className="w-full h-full">
        <FlowbiteInitializer />
        <div className="flex w-full min-h-screen">
          {/* Sidebar */}
          {isAuthPage ? ('') : (<Sidebar />)}

          {/* Main content */}
          <main className="flex-1 w-full p-4 bg-white dark:bg-black">
            {children}
          </main>
        </div>
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: '#363636',
              color: '#fff',
            },
            success: {
              duration: 3000,
            },
            error: {
              duration: 4000,
            },
          }}
        />
      </body>
    </html>
  );
}
